title: "Curso MCA"
logo: "/assets/images/fauba-logo.png"
#remote_theme: pmarsceill/just-the-docs
remote_theme: just-the-docs/just-the-docs
#theme: just-the-docs
color_scheme: fauba
exclude : [readme, tut/futuro, tut/archivos,tps/archivos]
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
plugins:
  - jemoji
defaults:
  -
    scope:
      path: "" #an empty string here means all files in the project
    values:
      #layout: "page"
      has_children: true
      has_toc: true
      nav_order: 2
  - 
    scope:
      path: "teo"
    values:
      parent: Teóricas
      has_children: false
  -
    scope:
      path: "tps"
    values:
      parent: Trabajos Prácticos
      has_children: false
  -
    scope:
      path: "tut" 
    values:
      parent: Tutoriales
      has_children: false
  -
    scope:
      path: "ejs"
    values:
      parent: Ejercicios
      has_children: false

